In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [375]:
arr1  =cv2.imread(r"2.jpg")
print(arr1.shape)
arrg=cv2.cvtColor(arr1, cv2.COLOR_BGR2GRAY)

(982, 1900, 3)


In [3]:
%matplotlib qt 

In [395]:
plt.figure(figsize=(10, 10))
plt.imshow(arrg[:,:300])
plt.show()

In [20]:
nine=small[1:12,44:50]
nine.shape

(11, 6)

In [22]:
nine[nine>=190]=255
nine[nine<190]=0
nine

array([[255,   0,   0,   0,   0, 255],
       [  0,   0, 255, 255,   0,   0],
       [  0, 255, 255, 255, 255,   0],
       [  0, 255, 255, 255, 255,   0],
       [  0,   0, 255, 255, 255,   0],
       [  0,   0, 255, 255,   0,   0],
       [255,   0,   0,   0,   0,   0],
       [255, 255, 255, 255, 255,   0],
       [255, 255, 255, 255,   0,   0],
       [  0, 255, 255,   0,   0, 255],
       [255,   0,   0,   0, 255, 255]], dtype=uint8)

In [285]:
arrg[arrg>=190]=255
arrg[arrg<190]=0

In [ ]:
small[1:12,17:23]

In [379]:
def ocrPriceArr(price_arr,precision=2,len=5):
    digit_arr=[]
    y=price_arr.shape[1]
    #left of dot
    for i in range(precision):
        digit_arr.append(price_arr[:, y - digit_width:y])
        y = y - digit_width - digit_sep
    y=y-dot_width-digit_sep
    #right of dot
    for i in range(len-precision):
        digit_arr.append(price_arr[:, y - digit_width:y])
        y = y - digit_width - digit_sep

In [356]:
digit_width=6
digit_sep=2
colon_width=1
def ocrTime(coltime):
    y=coltime.shape[1]
    hight=coltime.shape[0]
    second1=coltime[:,y-digit_width:y]
    y=y-digit_width-digit_sep
    second2=coltime[:,y-digit_width:y]
    y=y-digit_width-digit_sep-colon_width-digit_sep
    minute1=coltime[:,y-digit_width:y]
    y=y-digit_width-digit_sep
    minute2=coltime[:,y-digit_width:y]
    y=y-digit_width-digit_sep-colon_width-digit_sep
    hour1=coltime[:,y-digit_width:y]
    return (hour1,minute2,minute1,second2,second1)

In [54]:
zero_marsk=ocrTime(small[1:12,:50])!=zero

In [55]:
np.logical_or(ocrTime(small[1:12,:50])==zero ,zero_marsk).all()

True

In [58]:
char=[None]*20
marsk=[None]*20

In [66]:
plt.imshow(small[12+6:12+6+11,:50])
plt.show()

In [69]:
char[2]=ocrTime(small[12+6:12+6+11,:50])

In [75]:
np.logical_or(ocrTime(small[12+6:12+6+11,:50])[3]==zero ,zero_marsk).all()

True

In [111]:
timetuple=ocrTime(small[12+6:12+6+11,:50])
timetuple[0]

array([[255,   0,   0,   0,   0, 255],
       [  0,   0, 255, 255,   0,   0],
       [  0,   0, 255, 255, 255,   0],
       [  0, 255, 255, 255, 255,   0],
       [  0, 255, 255, 255, 255,   0],
       [  0, 255, 255, 255, 255,   0],
       [  0, 255, 255, 255, 255,   0],
       [  0, 255, 255, 255, 255,   0],
       [  0,   0, 255, 255,   0,   0],
       [  0,   0, 255, 255,   0,   0],
       [255,   0,   0,   0,   0, 255]], dtype=uint8)

In [76]:
char[1]=ocrTime(small[12+6:12+6+11,:50])[1]
char[1]

array([[255, 255, 255,   0, 255, 255],
       [255,   0,   0,   0, 255, 255],
       [  0,   0, 255,   0,   0, 255],
       [255, 255, 255,   0, 255, 255],
       [255, 255, 255,   0, 255, 255],
       [255, 255, 255,   0, 255, 255],
       [255, 255, 255,   0, 255, 255],
       [255, 255, 255,   0, 255, 255],
       [255, 255, 255,   0, 255, 255],
       [255, 255, 255,   0, 255, 255],
       [255, 255, 255,   0, 255, 255]], dtype=uint8)

In [363]:
def ocrStr(arr,last=None):
    if last is not None:
        if np.logical_or(arr ==digit_arr[last] ,digt_marsk_arr[last]).all():
            return 1,str(last)
    else:
        for (cid,c) in enumerate( digit_arr):
            if np.logical_or(arr ==digit_arr[cid] ,digt_marsk_arr[cid]).all():
                return 1,str(cid)
    return 0,arr

In [322]:
import pdb 

def ocrTimeCol(coltime):
#     pdb.set_trace()
    x=1 #config
#     total is 57 row
    lasttime="start"
    for i in range( round(coltime.shape[0]/17)-1):       
        temp=ocrTime(coltime[x:x+11,:])
        if (temp[0]==empty).all():
            print(lasttime)
        else:
            outstr=""
            ret,tempret=ocrStr(temp[0])
            if  not ret:
                print(tempret)
                break
            outstr=outstr+tempret
            ret,tempret=ocrStr(temp[1])
            if  not ret:
                print(tempret)
                break
            outstr=outstr+tempret
            ret,tempret=ocrStr(temp[2])
            if  not ret:
                print(tempret)
                break
            outstr=outstr+tempret
            ret,tempret=ocrStr(temp[3])
            if  not ret:
                print(tempret)
                break
            outstr=outstr+tempret
            ret,tempret=ocrStr(temp[4])
            if  not ret:
                print(tempret)
                break
            outstr=outstr+tempret
            print(i,outstr)
            lasttime=outstr
        x=x+11+6
        
    return tempret

In [ ]:
def ocrAlltime(arr):
    

In [85]:
timearr=ocrTimeCol(small[:,:50])

In [92]:
plt.imshow(timearr[-2])
plt.show()

In [91]:
char[-1]=ocrTime(timearr[3])[1]

In [103]:
for i in range(len(marsk)):
    if  marsk[i] is None:
        marsk[i] = marsk[-1]

In [108]:
if not 0:
    print(1)

1


In [148]:

plt.imshow(ocrTimeCol(small[:,:50]))
plt.show()

00959
01002
01005
01005
01007
01008
01008
01008
01008
01008
01008
01008
01010
01010
01010
01017
01018
01021
01021
[[255 255 255   0 255 255]
 [255   0   0   0 255 255]
 [  0   0 255   0 255 255]
 [255 255 255   0 255 255]
 [255 255 255   0 255 255]
 [255 255 255   0 255 255]
 [255 255 255   0 255 255]
 [255 255 255   0 255 255]
 [255 255 255   0   0 255]
 [255 255 255   0 255 255]
 [255 255 255   0 255 255]]


In [211]:
marsk[5]=np.logical_or((ocrTimeCol(small[:,:50+317])!=char[5]),marsk[5])
marsk[5]

start
01124
[[255   0   0   0   0   0]
 [255   0 255 255 255 255]
 [  0   0 255 255 255 255]
 [  0   0 255 255 255 255]
 [  0   0 255 255 255 255]
 [  0   0   0   0   0 255]
 [255 255 255 255   0   0]
 [255 255 255 255   0   0]
 [255 255 255 255 255   0]
 [  0 255 255 255   0   0]
 [  0   0   0   0   0 255]]


array([[ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [346]:
def updateMarsk(id,arr):
    #pdb.set_trace()
    if marsk[id] is None:
        marsk[id]=(arr!=char[id])
    else:
        print("before update marsk:",id)
        print(marsk[id])
        print(np.sum(marsk[id]))
        marsk[id]
        new=np.logical_or((arr!=char[id]),marsk[id])
    print("after update marsk:",)
    print(new)
    errsum=np.sum(new)
    print(errsum)
    if errsum>10:
        print("not update marsk id {} for error {} >10".format(id,errsum))
    else:
        marsk[id]=new
    return errsum

In [341]:
def findMatch(arr):
    bestid=0
    besterr=1000
    for (cid,c) in enumerate( char):
        currenterr=np.sum(arr != c)
        if besterr>currenterr:
            besterr=currenterr
            bestid=cid
    return bestid,besterr

In [300]:
plt.imshow(arrg[1:,:50])
plt.show()

In [364]:
# pdb.set_trace()
arr=ocrTimeCol(arrg[:,:50+317+317+317+317+317]) 
while not isinstance(arr,str):
    
    
    cid,errnum=findMatch(arr)
    if errnum >10:
        print("not findMatch  cid {} errnum {}!".format(cid,errnum))
    if updateMarsk(cid,arr) >10:
        break
    arr=ocrTimeCol(arrg[:,:50+317+317+317+317+317])    

start
start
2 02257
02257
4 02305
5 02312
02312
7 02314
8 02323
9 02348
10 02401
11 02429
02429
02429
02429
15 02535
02535
17 02536
02536
02536
02536
02536
22 02537
02537
02537
02537
02537
02537
02537
02537
30 02542
31 02602
02602
02602
02602
35 02651
02651
37 02720
02720
39 02722
02722
02722
42 02726
43 02804
02804
45 02807
46 02818
47 02838
48 02913
02913
02913
51 02917
02917
02917
02917
02917
02917


In [272]:
a=1
isinstance ( a,int)

True

In [338]:
marsk= [empty == (empty-1)]*10

In [369]:
import pickle
data_output = open('ocr_conf.pkl','wb')

In [370]:
pickle.dump((char,marsk,empty),data_output)

In [371]:
data_output.close()

In [372]:
data_input = open('ocr_conf.pkl','rb')
(digit_arr,digt_marsk_arr,empty_arr) = pickle.load(data_input)
data_input.close()

In [362]:
digit_arr

[array([[255,   0,   0,   0,   0, 255],
        [  0,   0, 255, 255,   0,   0],
        [  0,   0, 255, 255,   0,   0],
        [  0, 255, 255, 255, 255,   0],
        [  0, 255, 255, 255, 255,   0],
        [  0, 255, 255, 255, 255,   0],
        [  0, 255, 255, 255, 255,   0],
        [  0, 255, 255, 255, 255,   0],
        [  0,   0, 255, 255,   0,   0],
        [  0,   0, 255, 255,   0,   0],
        [255,   0,   0,   0,   0, 255]], dtype=uint8),
 array([[255, 255, 255,   0, 255, 255],
        [255,   0,   0,   0, 255, 255],
        [  0,   0, 255,   0,   0, 255],
        [255, 255, 255,   0, 255, 255],
        [255, 255, 255,   0, 255, 255],
        [255, 255, 255,   0, 255, 255],
        [255, 255, 255,   0, 255, 255],
        [255, 255, 255,   0, 255, 255],
        [255, 255, 255,   0, 255, 255],
        [255, 255, 255,   0, 255, 255],
        [255, 255, 255,   0, 255, 255]], dtype=uint8),
 array([[255,   0,   0,   0,   0, 255],
        [  0,   0, 255, 255,   0,   0],
        [2

In [368]:
round(4.33)

4

In [381]:
a="afg"[::-1]

In [382]:
def f(a):
    a[0]="b"

In [385]:
a[0]='b'

TypeError: 'str' object does not support item assignment

In [388]:
[ int(x) for x  in   "123444"]

[1, 2, 3, 4, 4, 4]

In [391]:
def myf(a=""):
    print(a)
    a="b"
    print(a)


In [393]:
c="sdf"
myf(c)

sdf
b


In [394]:
c

'sdf'

In [1]:
float("12.3")

12.3